Parameters:
  SNSTopicName:
    Description:  SNS Topic Name
    Type: String
    Default: Izaan-Test-GeneralAlarmNotificationSnsTopic
    AllowedValues:
      - Izaan-Test-GeneralAlarmNotificationSnsTopic
      - Izaan-UAT-GeneralAlarmNotificationSnsTopic
      - Izaan-Prod-GeneralAlarmNotificationSnsTopic
  SNSTopicSubscriberEndpoint:
    Description: SNS Topic Name
    Type: String
    Default: testdata.islam@gmail.com

Resources:
#  S3Bucket:
#    Type: AWS::S3::Bucket
#    Properties:
#      BucketName: my-bucket-your-bucket-my-bucket
#  WebServer:
#    Type: AWS::EC2::Instance
#    Properties:
#      ImageId: "ami-0c02fb55956c7d316"
#      KeyName: "qaaeb2102"
#      InstanceType: "t2.micro"
#      BlockDeviceMappings:
#        - DeviceName: "/dev/sdm"
#          Ebs:
#            VolumeType: "io1"
#            Iops: "200"
#            DeleteOnTermination: "false"
#            VolumeSize: "20"
#        - DeviceName: "/dev/sdk"
#          NoDevice: { }
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref SNSTopicSubscriberEndpoint
          Protocol: "email"
      TopicName: !Ref SNSTopicName

Outputs:
  MySNSTopicArn:
    Value: !Ref MySNSTopic
    Description: MySNSTopic Arn
  MySNSTopicName:
    Value: !GetAtt MySNSTopic.TopicName
    Description: MySNSTopic Name




# aws cloudformation create-stack --stack-name myteststack --template-body file://sampletemplate.json --parameters

